<?php

namespace App\Imports;

use Carbon\Carbon;
use Illuminate\Support\Collection;
use App\Models\UploadSalaryDetails;
use Maatwebsite\Excel\Concerns\ToModel;

class SalaryDetailsImport implements ToModel
{
    /**
     * @param Collectioncollection
     */
    public function model(array $value)
    {

        // foreach ($values as $value) {
        // dd($value);
        // $employee_id           = $value[0],
        // $employee_name         = $value[1],
        // $month_of_salary       = $value[2],
        // $designation           = $value[3],
        // $department            = $value[4],
        // $basic_salary          = $value[5],
        // $arrs                  = $value[6],
        // $total_overtime_amount = $value[7],
        // $ta                    = $value[8],
        // $refund                = $value[9],
        // $tds                   = $value[10],
        // $pf                    = $value[11],
        // $esi                   = $value[12],
        // $e_bill                = $value[13],
        // $trans_charge          = $value[14],
        // $adv                   = $value[15],
        // $acco                  = $value[16],
        // $prof_tax              = $value[17],
        // $total_absence_amount  = $value[18],
        // $total_earning         = $value[19],
        // $total_deduction       = $value[20],
        // $net_salary            = $value[21],
        // $gross_salary          = $value[22],
        // $created_at            = Carbon::now();
        // $updated_at            = Carbon::now();
        // $data = [

        return new UploadSalaryDetails([

                'employee_id'           => $value[0],
                'employee_name'         => $value[1],
                'month_of_salary'       => $value[2],
                'designation'           => $value[3],
                'department'            => $value[4],
                'basic_salary'          => $value[5],
                'arrs'                  => $value[6],
                'total_overtime_amount' => $value[7],
                'ta'                    => $value[8],
                'refund'                => $value[9],
                'tds'                   => $value[10],
                'pf'                    => $value[11],
                'esi'                   => $value[12],
                'e_bill'                => $value[13],
                'trans_charge'          => $value[14],
                'adv'                   => $value[15],
                'acco'                  => $value[16],
                'prof_tax'              => $value[17],
                'total_absence_amount'  => $value[18],
                'total_earning'         => $value[19],
                'total_deduction'       => $value[20],
                'net_salary'            => $value[21],
                'gross_salary'          => $value[22],
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),

            // $employee_id = $value[0],
            // $employee_name = $value[1],
            // $month_of_salary = $value[2],
            // $designation = $value[3],
            // $department = $value[4],
            // $basic_salary = $value[5],
            // $arrs = $value[6],
            // $total_overtime_amount = $value[7],
            // $ta = $value[8],
            // $refund = $value[9],
            // $tds = $value[10],
            // $pf = $value[11],
            // $esi = $value[12],
            // $e_bill = $value[13],
            // $trans_charge = $value[14],
            // $adv = $value[15],
            // $acco = $value[16],
            // $prof_tax = $value[17],
            // $total_absence_amount = $value[18],
            // $total_earning = $value[19],
            // $total_deduction = $value[20],
            // $net_salary = $value[21],
            // $gross_salary = $value[22],
            // // $created_at = Carbon::now(),
            // // $updated_at = Carbon::now(),

            // 'employee_name'         => $employee_name,
            // 'employee_id'           => $employee_id,
            // 'month_of_salary'       => $month_of_salary,
            // 'designation'           => $designation,
            // 'department'            => $department,
            // 'basic_salary'          => $basic_salary,
            // 'arrs'                  => $arrs,
            // 'total_overtime_amount' => $total_overtime_amount,
            // 'ta'                    => $ta,
            // 'refund'                => $refund,
            // 'tds'                   => $tds,
            // 'pf'                    => $pf,
            // 'esi'                   => $esi,
            // 'e_bill'                => $e_bill,
            // 'trans_charge'          => $trans_charge,
            // 'adv'                   => $adv,
            // 'acco'                  => $acco,
            // 'prof_tax'              => $prof_tax,
            // 'total_absence_amount'  => $total_absence_amount,
            // 'total_earning'         => $total_earning,
            // 'total_deduction'       => $total_deduction,
            // 'net_salary'            => $net_salary,
            // 'gross_salary'          => $gross_salary,
            // 'created_at'            => Carbon::now(),
            // 'updated_at'            => Carbon::now(),
            // ],

            // 'employee_name'         => $employee_name,
            // 'employee_id'           => $employee_id,
            // 'month_of_salary'       => $month_of_salary,
            // 'designation'           => $designation,
            // 'department'            => $department,
            // 'basic_salary'          => $basic_salary,
            // 'arrs'                  => $arrs,
            // 'total_overtime_amount' => $total_overtime_amount,
            // 'ta'                    => $ta,
            // 'refund'                => $refund,
            // 'tds'                   => $tds,
            // 'pf'                    => $pf,
            // 'esi'                   => $esi,
            // 'e_bill'                => $e_bill,
            // 'trans_charge'          => $trans_charge,
            // 'adv'                   => $adv,
            // 'acco'                  => $acco,
            // 'prof_tax'              => $prof_tax,
            // 'total_absence_amount'  => $total_absence_amount,
            // 'total_earning'         => $total_earning,
            // 'total_deduction'       => $total_deduction,
            // 'net_salary'            => $net_salary,
            // 'gross_salary'          => $gross_salary,
            // 'created_at'            => Carbon::now(),
            // 'updated_at'            => Carbon::now(),
            // $employee_id = $value[0],
            // $employee_name = $value[1],
            // $month_of_salary = $value[2],
            // $designation = $value[3],
            // $department = $value[4],
            // $basic_salary = $value[5],
            // $arrs = $value[6],
            // $total_overtime_amount = $value[7],
            // $ta = $value[8],
            // $refund = $value[9],
            // $tds = $value[10],
            // $pf = $value[11],
            // $esi = $value[12],
            // $e_bill = $value[13],
            // $trans_charge = $value[14],
            // $adv = $value[15],
            // $acco = $value[16],
            // $prof_tax = $value[17],
            // $total_absence_amount = $value[18],
            // $total_earning = $value[19],
            // $total_deduction = $value[20],
            // $net_salary = $value[21],
            // $gross_salary = $value[22],
            // $created_at = Carbon::now(),
            // $updated_at = Carbon::now(),
            // 'employee_id'           => $value[0],
            // 'employee_name'         => $value[1],
            // 'month_of_salary'       => $value[2],
            // 'designation'           => $value[3],
            // 'department'            => $value[4],
            // 'basic_salary'          => $value[5],
            // 'arrs'                  => $value[6],
            // 'total_overtime_amount' => $value[7],
            // 'ta'                    => $value[8],
            // 'refund'                => $value[9],
            // 'tds'                   => $value[10],
            // 'pf'                    => $value[11],
            // 'esi'                   => $value[12],
            // 'e_bill'                => $value[13],
            // 'trans_charge'          => $value[14],
            // 'adv'                   => $value[15],
            // 'acco'                  => $value[16],
            // 'prof_tax'              => $value[17],
            // 'total_absence_amount'  => $value[18],
            // 'total_earning'         => $value[19],
            // 'total_deduction'       => $value[20],
            // 'net_salary'            => $value[21],
            // 'gross_salary'          => $value[22],
            // 'created_at'            => Carbon::now(),
            // 'updated_at'            => Carbon::now(),
        ]);
        // dd($data);

        //    DB::table('upload_salary_details')->insert([$data]);
    }
}
// public function headingRow(): int
// {
//     return 2;
// }
// }
